/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import {
  useGLTF,
  PerspectiveCamera,
  useAnimations,
  useTexture,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model({ scroll, ...props }) {
  const group = useRef();
  const [hovered, setHovered] = useState(false);
  const { nodes, animations } = useGLTF("./model/actions.glb");
  const { actions } = useAnimations(animations, group);

  //
  const cubeTexture = useTexture("./model/CubeSample.jpg");
  cubeTexture.flipY = false;
  cubeTexture.encoding = THREE.sRGBEncoding;
  const CubeMaterial = new THREE.MeshStandardMaterial({ map: cubeTexture });

  // const sofaTexture = useTexture("./model/SofaSample.jpg");
  // sofaTexture.flipY = false;
  // sofaTexture.encoding = THREE.sRGBEncoding;
  // const sofaMaterial = new THREE.MeshStandardMaterial({ map: sofaTexture });

  // const blackishTexture = useTexture("./model/BlackishSample.jpg");
  // blackishTexture.flipY = false;
  // blackishTexture.encoding = THREE.sRGBEncoding;
  // const blackishMaterial = new THREE.MeshStandardMaterial({
  //   map: blackishTexture,
  // });

  // const furnitureTexture = useTexture("./model/FurnitureSample.jpg");
  // furnitureTexture.flipY = false;
  // furnitureTexture.encoding = THREE.sRGBEncoding;
  // const furnitureMaterial = new THREE.MeshStandardMaterial({
  //   map: furnitureTexture,
  // });

  // const OtherTexture = useTexture("./model/OtherSample.jpg");
  // OtherTexture.flipY = false;
  // OtherTexture.encoding = THREE.sRGBEncoding;
  // const OtherMaterial = new THREE.MeshStandardMaterial({
  //   map: OtherTexture,
  // });
  //

  // useEffect(() => {
  //   const action = actions["CameraAction.001"];
  //   action.play().paused = true;
  //   return () => {
  //     action.stop();
  //   };
  // }, [actions]);

  console.log("break");

  // useEffect(() => void (actions["CameraAction.001"].play().paused = true), []);

  // console.log(actions);

  // useFrame((state) => {
  //   console.log("Scroll:", scroll.current);
  //   actions["CameraAction.001"].time = THREE.MathUtils.lerp(
  //     actions["CameraAction.001"].time,
  //     actions["CameraAction.001"].getClip().duration * scroll.current,
  //     0.05
  //   );
  // });

  useEffect(() => {
    // Play both animations, but keep them paused initially
    void (actions["CameraAction.001"].play().paused = true);
    void (actions["Spider-Man No Way Home SuitAction"].play().paused = true);
  }, [actions]);

  useFrame((state) => {
    const scrollValue = scroll.current;

    // Update both animations based on scroll
    const cameraAction = actions["CameraAction.001"];
    const spiderManAction = actions["Spider-Man No Way Home SuitAction"];

    cameraAction.time = THREE.MathUtils.lerp(
      cameraAction.time,
      cameraAction.getClip().duration * scrollValue,
      0.05
    );

    spiderManAction.time = THREE.MathUtils.lerp(
      spiderManAction.time,
      spiderManAction.getClip().duration * scrollValue,
      0.05
    );
  });

  const amazonTexture = useTexture("./model/amazon.png");
  amazonTexture.flipY = true;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Sofa"
          geometry={nodes.Sofa.geometry}
          material={nodes.Sofa.material}
          position={[12.921, 0, 0]}
        />
        <mesh
          name="Furniture"
          geometry={nodes.Furniture.geometry}
          material={nodes.Furniture.material}
          position={[62.364, 6.809, -41.729]}
          rotation={[Math.PI / 2, 0, 0.458]}
        />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={CubeMaterial}
        />
        <mesh
          name="Black"
          geometry={nodes.Black.geometry}
          material={nodes.Black.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="EmissionTxt"
          geometry={nodes.EmissionTxt.geometry}
          material={nodes.EmissionTxt.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Green"
          geometry={nodes.Green.geometry}
          material={nodes.Green.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <PerspectiveCamera
          name="Camera"
          makeDefault
          far={1000}
          near={0.1}
          fov={37.299}
          position={[-28.036, 28.953, 0.975]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="EmissionDown"
          geometry={nodes.EmissionDown.geometry}
          material={nodes.EmissionDown.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="ClockWhite"
          geometry={nodes.ClockWhite.geometry}
          material={nodes.ClockWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="ClockBlack"
          geometry={nodes.ClockBlack.geometry}
          material={nodes.ClockBlack.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="TVPicture"
          geometry={nodes.TVPicture.geometry}
          material={nodes.TVPicture.material}
        />
        <mesh
          name="OtherBlack"
          geometry={nodes.OtherBlack.geometry}
          material={nodes.OtherBlack.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="OtherWhite"
          geometry={nodes.OtherWhite.geometry}
          material={nodes.OtherWhite.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="HeadphoneRed"
          geometry={nodes.HeadphoneRed.geometry}
          material={nodes.HeadphoneRed.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="OtherEmission"
          geometry={nodes.OtherEmission.geometry}
          material={nodes.OtherEmission.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="OtherGlass"
          geometry={nodes.OtherGlass.geometry}
          material={nodes.OtherGlass.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="OtherGlossyWood"
          geometry={nodes.OtherGlossyWood.geometry}
          material={nodes.OtherGlossyWood.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="ConsoleRed"
          geometry={nodes.ConsoleRed.geometry}
          material={nodes.ConsoleRed.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="ConsoleYellow"
          geometry={nodes.ConsoleYellow.geometry}
          material={nodes.ConsoleYellow.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="OtherGrey"
          geometry={nodes.OtherGrey.geometry}
          material={nodes.OtherGrey.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="Blackish_Emission"
          geometry={nodes.Blackish_Emission.geometry}
          material={nodes.Blackish_Emission.material}
        />
        <mesh
          name="Blackish"
          geometry={nodes.Blackish.geometry}
          material={nodes.Blackish.material}
        />
        <mesh
          name="Books"
          geometry={nodes.Books.geometry}
          material={nodes.Books.material}
          position={[88.376, 6.809, -107.37]}
          rotation={[Math.PI / 2, 0, 0.458]}
        />
        <mesh
          name="ResumeBlackFrame"
          geometry={nodes.ResumeBlackFrame.geometry}
          material={nodes.ResumeBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="ResumeWhite"
          geometry={nodes.ResumeWhite.geometry}
          material={nodes.ResumeWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="ResumePicture"
          geometry={nodes.ResumePicture.geometry}
          material={nodes.ResumePicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="AmazonPicture"
          geometry={nodes.AmazonPicture.geometry}
          material={nodes.AmazonPicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="AmazonBlackFrame"
          geometry={nodes.AmazonBlackFrame.geometry}
          material={nodes.AmazonBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="AmazonWhite"
          geometry={nodes.AmazonWhite.geometry}
          material={nodes.AmazonWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="PortalPicture"
          geometry={nodes.PortalPicture.geometry}
          material={nodes.PortalPicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="PortalBlackFrame"
          geometry={nodes.PortalBlackFrame.geometry}
          material={nodes.PortalBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="PortalWhite"
          geometry={nodes.PortalWhite.geometry}
          material={nodes.PortalWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="MugavariPicture"
          geometry={nodes.MugavariPicture.geometry}
          material={nodes.MugavariPicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="MugavariBlackFrame"
          geometry={nodes.MugavariBlackFrame.geometry}
          material={nodes.MugavariBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="MugavariWhite"
          geometry={nodes.MugavariWhite.geometry}
          material={nodes.MugavariWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SpacePicture"
          geometry={nodes.SpacePicture.geometry}
          material={nodes.SpacePicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SpaceBlackFrame"
          geometry={nodes.SpaceBlackFrame.geometry}
          material={nodes.SpaceBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SpaceWhite"
          geometry={nodes.SpaceWhite.geometry}
          material={nodes.SpaceWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Gb1Picture"
          geometry={nodes.Gb1Picture.geometry}
          material={nodes.Gb1Picture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="GB1BlackFrame"
          geometry={nodes.GB1BlackFrame.geometry}
          material={nodes.GB1BlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="GB1White"
          geometry={nodes.GB1White.geometry}
          material={nodes.GB1White.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="GB2Picture"
          geometry={nodes.GB2Picture.geometry}
          material={nodes.GB2Picture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="GB2BlackFrame"
          geometry={nodes.GB2BlackFrame.geometry}
          material={nodes.GB2BlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="GB2White"
          geometry={nodes.GB2White.geometry}
          material={nodes.GB2White.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="EcommercePicture"
          geometry={nodes.EcommercePicture.geometry}
          material={nodes.EcommercePicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="EcommerceBlackFrame"
          geometry={nodes.EcommerceBlackFrame.geometry}
          material={nodes.EcommerceBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="EcommerceWhite"
          geometry={nodes.EcommerceWhite.geometry}
          material={nodes.EcommerceWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SriPicture"
          geometry={nodes.SriPicture.geometry}
          material={nodes.SriPicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SriBlackFrame"
          geometry={nodes.SriBlackFrame.geometry}
          material={nodes.SriBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SriWhite"
          geometry={nodes.SriWhite.geometry}
          material={nodes.SriWhite.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SchoolPicture"
          geometry={nodes.SchoolPicture.geometry}
          material={nodes.SchoolPicture.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SchoolBlackFrame"
          geometry={nodes.SchoolBlackFrame.geometry}
          material={nodes.SchoolBlackFrame.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="SchoolWhite"
          geometry={nodes.SchoolWhite.geometry}
          material={nodes.SchoolWhite.material}
        />
        <mesh
          name="MjolnierGold"
          geometry={nodes.MjolnierGold.geometry}
          material={nodes.MjolnierGold.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="MjolnierSteel"
          geometry={nodes.MjolnierSteel.geometry}
          material={nodes.MjolnierSteel.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <mesh
          name="Mjolnier_Brown"
          geometry={nodes.Mjolnier_Brown.geometry}
          material={nodes.Mjolnier_Brown.material}
          position={[-5.003, 0, 0]}
          rotation={[0, 0.283, 0]}
        />
        <group name="Sport_cup" position={[-16.555, 27.942, -42.752]}>
          <mesh
            name="hands"
            geometry={nodes.hands.geometry}
            material={nodes.hands.material}
            position={[1.342, 2.387, -0.387]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            name="Text"
            geometry={nodes.Text.geometry}
            material={nodes.Text.material}
            position={[-0.479, 2.539, 0.753]}
            rotation={[1.312, 0, 0]}
          />
        </group>
        <group
          name="Viking_Axe"
          position={[-14.507, 6.714, -43.121]}
          rotation={[0, 0, -0.045]}
        >
          <mesh
            name="Plane002"
            geometry={nodes.Plane002.geometry}
            material={nodes.Plane002.material}
            position={[0.517, 13.252, -1.023]}
            rotation={[1.446, 0.086, 2.581]}
          />
          <mesh
            name="Plane003"
            geometry={nodes.Plane003.geometry}
            material={nodes.Plane003.material}
            position={[0.515, 13.267, -1.025]}
            rotation={[1.446, 0.086, 2.581]}
          />
        </group>
        <group
          name="Ps4_fat_with_very_light_scratches"
          position={[-52.396, 9.896, 6.5]}
        >
          <mesh
            name="aux"
            geometry={nodes.aux.geometry}
            material={nodes.aux.material}
            position={[-1.579, 0.758, -1.003]}
            rotation={[-Math.PI, 1.562, -Math.PI]}
          />
        </group>
        <group
          name="PS3_Dualshock_Controller_Gamepad"
          position={[-47.121, 9.892, 2.695]}
        >
          <mesh
            name="analogic_buttons"
            geometry={nodes.analogic_buttons.geometry}
            material={nodes.analogic_buttons.material}
            position={[0, 0.016, 0.008]}
            rotation={[-0.172, 0, 0]}
          />
        </group>
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[62.775, 0.171, 21.083]}
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={nodes.Plane001.material}
          position={[62.717, 23.565, 20.981]}
        />
        <group
          name="Spider-Man_No_Way_Home_Suit"
          position={[-7.013, 1.905, -19.292]}
          rotation={[-Math.PI, 1.541, -Math.PI]}
        >
          <group
            name="Spiderman_model"
            position={[0, 15.125, 0]}
            rotation={[0, 0.302, 0]}
          >
            <skinnedMesh
              name="lens_blackout"
              geometry={nodes.lens_blackout.geometry}
              material={nodes.lens_blackout.material}
              skeleton={nodes.lens_blackout.skeleton}
            />
            <skinnedMesh
              name="lens1"
              geometry={nodes.lens1.geometry}
              material={nodes.lens1.material}
              skeleton={nodes.lens1.skeleton}
            />
            <skinnedMesh
              name="lense_covers"
              geometry={nodes.lense_covers.geometry}
              material={nodes.lense_covers.material}
              skeleton={nodes.lense_covers.skeleton}
              morphTargetDictionary={nodes.lense_covers.morphTargetDictionary}
              morphTargetInfluences={nodes.lense_covers.morphTargetInfluences}
            />
            <skinnedMesh
              name="Spiderman"
              geometry={nodes.Spiderman.geometry}
              material={nodes.Spiderman.material}
              skeleton={nodes.Spiderman.skeleton}
            />
            <primitive object={nodes.spine1} />
            <primitive object={nodes.spine1child} />
            <primitive object={nodes.hipL} />
            <primitive object={nodes.buttL} />
            <primitive object={nodes.hipR} />
            <primitive object={nodes.buttR} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./model/actions.glb");
