/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room2.2.glb -k 
*/

import * as THREE from "three";
import gohanImg from "./assets/webp/gohans.webp";
import zoroImg from "./assets/webp/zoro.webp";
import itachiImg from "./assets/webp/itachi.webp";
import luffyImg from "./assets/webp/luffyss.webp";
import spiderImg from "./assets/webp/spider.webp";
import batmanImg from "./assets/webp/batman.webp";
import xodaImg from "./assets/webp/xoda.webp";
import wowhrImg from "./assets/webp/wowhr.webp";
import swifinImg from "./assets/webp/swifin.webp";
import adminImg from "./assets/webp/admin.webp";
import spaceImg from "./assets/webp/space.webp";
import mugavariImg from "./assets/webp/mugavari.webp";
import gb11Img from "./assets/webp/gb11.webp";
import gb22Img from "./assets/webp/gb22.webp";
import fjordImg from "./assets/webp/fjord.webp";
import amazonImg from "./assets/webp/amazon.webp";
import ad2dImg from "./assets/webp/ad2d.webp";
import portalImg from "./assets/webp/portal.webp";
import tvImageImg from "./assets/webp/tvImage.webp";
import ecommerceImg from "./assets/webp/ecommerce.webp";
import introImg from "./assets/webp/intros.webp";
import htmlCssImg from "./assets/webp/html.webp";
import reactjsImg from "./assets/webp/reactjs.webp";
import blenderImg from "./assets/webp/blender.webp";
import javascriptImg from "./assets/webp/javascript.webp";
import splineImg from "./assets/webp/spline.webp";
import threejsImg from "./assets/webp/threejs.webp";
import gsapImg from "./assets/webp/gsap.webp";
import tailwindcssImg from "./assets/webp/tailwindcss.webp";
import figmaImg from "./assets/webp/figma.webp";
import flutterImg from "./assets/webp/flutter.webp";
import ratingsImg from "./assets/webp/ratings.webp";
import unityImg from "./assets/webp/unity.webp";
import infoImg from "./assets/webp/info.webp";

import React, { useEffect, useRef, useState } from "react";
import {
  MeshTransmissionMaterial,
  PerspectiveCamera,
  shaderMaterial,
  useAnimations,
  useGLTF,
  useTexture,
} from "@react-three/drei";
import { extend, useFrame } from "@react-three/fiber";

export function Model({ justReset, bloomRef, scroll, ...props }) {
  const group = useRef();

  const { nodes, materials, animations } = useGLTF("/room2v2.2.glb");
  const { actions } = useAnimations(animations, group);

  const DragonBallGlowMaterial = shaderMaterial(
    {
      colorA: new THREE.Color("#FFE600"), // Bright Yellow
      colorB: new THREE.Color("#FF3C00"), // Fiery Orange
      intensity: 2.5,
    },
    ` // Vertex Shader
      varying vec2 vUv;
      void main() {
        vUv = uv;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `,
    ` // Fragment Shader
      uniform vec3 colorA;
      uniform vec3 colorB;
      uniform float intensity;
      varying vec2 vUv;
  
      void main() {
        float dist = distance(vUv, vec2(0.5));
        float glow = pow(1.0 - dist, 2.2) * intensity;
        vec3 color = mix(colorB, colorA, dist);
        gl_FragColor = vec4(color, glow);
      }
    `
  );
  extend({ DragonBallGlowMaterial });

  // Load all textures into a single object
  const textures = {
    gohanMaterial: useTexture(gohanImg),
    zoroMaterial: useTexture(zoroImg),
    itachiMaterial: useTexture(itachiImg),
    luffyMaterial: useTexture(luffyImg),
    spiderMaterial: useTexture(spiderImg),
    batmanMaterial: useTexture(batmanImg),
    xodaMaterial: useTexture(xodaImg),
    wowhrMaterial: useTexture(wowhrImg),
    swifinMaterial: useTexture(swifinImg),
    adminMaterial: useTexture(adminImg),
    spaceMaterial: useTexture(spaceImg),
    mugavariMaterial: useTexture(mugavariImg),
    gb11Material: useTexture(gb11Img),
    gb22Material: useTexture(gb22Img),
    fjordMaterial: useTexture(fjordImg),
    amazonMaterial: useTexture(amazonImg),
    ad2dMaterial: useTexture(ad2dImg),
    portalMaterial: useTexture(portalImg),
    tvImageMaterial: useTexture(tvImageImg),
    ecommerceMaterial: useTexture(ecommerceImg),
    introMaterial: useTexture(introImg),
    htmlCssMaterial: useTexture(htmlCssImg),
    reactjsMaterial: useTexture(reactjsImg),
    blenderMaterial: useTexture(blenderImg),
    javascriptMaterial: useTexture(javascriptImg),
    splineMaterial: useTexture(splineImg),
    threejsMaterial: useTexture(threejsImg),
    gsapMaterial: useTexture(gsapImg),
    tailwindcssMaterial: useTexture(tailwindcssImg),
    figmaMaterial: useTexture(figmaImg),
    flutterMaterial: useTexture(flutterImg),
    ratingsMaterial: useTexture(ratingsImg),
    unityMaterial: useTexture(unityImg),
    infoMaterial: useTexture(infoImg),
  };

  // Apply settings to all
  Object.values(textures).forEach((mat) => {
    mat.flipY = false;
    mat.encoding = THREE.sRGBEncoding;
  });

  //
  textures.tvImageMaterial.center.set(0.5, 0.5);
  textures.tvImageMaterial.rotation = Math.PI * 1.5;

  //
  textures.gohanMaterial.center.set(0.5, 0.5);
  textures.gohanMaterial.rotation = Math.PI * 1.5;

  //
  textures.zoroMaterial.center.set(0.5, 0.5);
  textures.zoroMaterial.rotation = Math.PI * 1.5;

  //
  textures.splineMaterial.center.set(0.5, 0.5);
  textures.splineMaterial.rotation = Math.PI / 2;

  //
  textures.gsapMaterial.repeat.x = -1;
  textures.gsapMaterial.center.set(0.5, 0.5);
  textures.gsapMaterial.rotation = Math.PI * 1.5;
  //

  //
  textures.infoMaterial.repeat.y = 1;
  textures.infoMaterial.center.set(0.5, 0.5);
  textures.infoMaterial.rotation = Math.PI;
  //

  const {
    gohanMaterial,
    zoroMaterial,
    itachiMaterial,
    luffyMaterial,
    spiderMaterial,
    batmanMaterial,
    xodaMaterial,
    wowhrMaterial,
    swifinMaterial,
    adminMaterial,
    spaceMaterial,
    mugavariMaterial,
    gb11Material,
    gb22Material,
    fjordMaterial,
    amazonMaterial,
    ad2dMaterial,
    portalMaterial,
    tvImageMaterial,
    ecommerceMaterial,
    introMaterial,
    htmlCssMaterial,
    reactjsMaterial,
    blenderMaterial,
    javascriptMaterial,
    splineMaterial,
    threejsMaterial,
    gsapMaterial,
    tailwindcssMaterial,
    figmaMaterial,
    flutterMaterial,
    ratingsMaterial,
    unityMaterial,
    infoMaterial,
  } = textures;

  //
  const justBakedTextures = useTexture("/Bakev2.2.jpg");
  justBakedTextures.flipY = false;

  justBakedTextures.encoding = THREE.sRGBEncoding;
  const justBakedMaterial = new THREE.MeshStandardMaterial({
    map: justBakedTextures,
  });

  //
  const [cameraActionName, setCameraActionName] = useState(
    "CameraActionDesktop"
  );
  const [fov, setFov] = useState(40); // default FOV
  useEffect(() => {
    function updateCameraTypeAndFOV() {
      const width = window.innerWidth;
      const height = window.innerHeight;

      const isPortrait = height > width;
      const isLandscape = width >= height;

      let newCameraType = "CameraActionDesktop";
      let newFov = 40;

      if (width <= 767 && isPortrait) {
        //console.log(height, width, "1", "potrait");
        newCameraType = "CameraActionMobile";
        newFov = 57;
      } else if (width <= 1024 && height <= 500 && isLandscape) {
        //console.log(height, width, "2", "Landscape");
        newCameraType = "CameraActionMobileLandscape";
        newFov = 31;
      } else if (width >= 768 && width <= 1024 && height > 500 && isPortrait) {
        //console.log(height, width, "3", "potrait");
        newCameraType = "CameraActionMobile";
        newFov = 50;
      } else if (width >= 1024 && width <= 1240 && isLandscape) {
        //console.log(height, width, "4", "landscape");
        newCameraType = "CameraActionDesktop";
        newFov = 60;
      } else if (width > 1240 && width <= 1367 && isLandscape) {
        //console.log(height, width, "5", "landcsape");
        newCameraType = "CameraActionDesktop";
        newFov = 60;
      } else {
        //console.log(height, width, "6", "else");
        newCameraType = "CameraActionDesktop";
        newFov = 50;
      }

      setCameraActionName((prev) => {
        if (prev !== newCameraType) {
          // console.log("[Camera Switch]", newCameraType);
        }
        return newCameraType;
      });

      setFov((prev) => {
        if (prev !== newFov) {
          // console.log("[FOV Change]", newFov);
        }
        return newFov;
      });
    }

    updateCameraTypeAndFOV(); // on load

    window.addEventListener("resize", updateCameraTypeAndFOV);
    return () => window.removeEventListener("resize", updateCameraTypeAndFOV);
  }, []);

  useEffect(() => {
    if (actions && actions[cameraActionName]) {
      Object.values(actions).forEach((action) => action.stop());
      actions[cameraActionName].reset().play().paused = true;
      // console.log(
      //   `[🎥] Playing camera: ${cameraActionName},
      //   ${window.innerWidth},${window.innerHeight}`
      // );
    }
  }, [actions, cameraActionName]);

  // Dynamic Camera End

  //   Camera scroll start
  const fan1Ref = useRef();
  const fan2Ref = useRef();
  const fan3Ref = useRef();
  const fan4Ref = useRef();

  const isTouchDevice = () =>
    typeof window !== "undefined" &&
    ("ontouchstart" in window || navigator.maxTouchPoints > 0);

  useFrame((state, delta) => {
    const speed = 1; // 🔁 Rev/sec

    [fan1Ref, fan2Ref, fan3Ref].forEach((fan) => {
      if (fan.current) {
        fan.current.rotation.x -= delta * speed * Math.PI * 2;
      }
    });

    [fan4Ref].forEach((fan) => {
      if (fan.current) {
        fan.current.rotation.y += delta * speed * Math.PI * 2;
      }
    });
    const scrollValue = scroll.current;
    const cameraAction = actions[cameraActionName];

    if (!cameraAction) return;

    const clampedScroll = Math.min(scroll.current, 0.999);
    // const clampedScroll = Math.min(
    //   isTouchDevice() ? scroll.current * 1.5 : scroll.current,
    //   0.999
    // );

    const targetTime = cameraAction.getClip().duration * clampedScroll;

    if (justReset.current) {
      cameraAction.time = targetTime;
      justReset.current = false;
      return;
    }

    cameraAction.time = THREE.MathUtils.lerp(
      cameraAction.time,
      targetTime,
      isTouchDevice() ? 0.07 : 0.05
      // 0.05
    );
  });

  //   Camera scroll end

  // Clock Start
  const hourRef = useRef();
  const minuteRef = useRef();
  const secondRef = useRef();

  useFrame(() => {
    const now = new Date();

    const hours = now.getHours() % 12;
    const minutes = now.getMinutes();
    const seconds = now.getSeconds();

    // Convert to radians (clock rotates clockwise, so use -angle)
    const secondRotation = (seconds / 60) * Math.PI * 2;
    const minuteRotation = (minutes / 60) * Math.PI * 2 + secondRotation / 60;
    const hourRotation = (hours / 12) * Math.PI * 2 + minuteRotation / 12;

    if (secondRef.current) secondRef.current.rotation.z = secondRotation;
    if (minuteRef.current) minuteRef.current.rotation.z = minuteRotation;
    if (hourRef.current) hourRef.current.rotation.z = hourRotation;

    // console.log(hours, minutes, seconds, hourRotation);
  });

  const sceneRef = useRef();
  const targetPosition = useRef({ x: 0, y: 0 });
  const [deviceType, setDeviceType] = useState("desktop");

  useEffect(() => {
    const determineDeviceType = () => {
      const width = window.innerWidth;
      const height = window.innerHeight;
      const isPortraitOrientation = height > width;
      const isLandscapeOrientation = width >= height;

      const isTouch =
        navigator.maxTouchPoints > 1 ||
        window.matchMedia("(pointer: coarse)").matches;

      const isLandscape =
        width <= 1024 && height <= 500 && isLandscapeOrientation;

      const isTabletLandscape =
        width >= 1024 && width <= 1367 && isLandscapeOrientation;

      if (isTouch && isLandscape) {
        //console.log("mobileLandscape");
        setDeviceType("mobileLandscape");
      } else if (isTouch && isTabletLandscape) {
        setDeviceType("tabletLandscape");
        //console.log("tabletLandscape");
      } else if (isTouch && isPortraitOrientation) {
        //console.log("mobile");
        setDeviceType("mobile");
      } else {
        //console.log("desktop");
        setDeviceType("desktop");
      }
    };

    determineDeviceType();
    window.addEventListener("resize", determineDeviceType);
    return () => window.removeEventListener("resize", determineDeviceType);
  }, []);

  useFrame((state) => {
    if (deviceType !== "desktop" || !sceneRef.current) return;

    const { mouse } = state;

    // 🎯 Calculate desired movement range
    targetPosition.current.x = THREE.MathUtils.clamp(mouse.x * 0.2, -0.2, 0.2); // left-right
    targetPosition.current.y = THREE.MathUtils.clamp(mouse.y * 0.2, -0.2, 0.2); // up-down

    // 🌀 Smooth movement (springy bounce)
    sceneRef.current.position.x +=
      (targetPosition.current.x - sceneRef.current.position.x) * 0.05;
    sceneRef.current.position.y +=
      (targetPosition.current.y - sceneRef.current.position.y) * 0.05;
  });

  //specific
  const swifinRef = useRef();
  const mugavariRef = useRef();
  const amazonRef = useRef();
  const wowhrRef = useRef();
  const xodaRef = useRef();
  const ad2dRef = useRef();
  const spaceRef = useRef();
  const ecommerceRef = useRef();
  const portalRef = useRef();
  const fjordRef = useRef();
  const gameBoyRef = useRef();
  const adminRef = useRef();
  const textRef = useRef();

  function animateText(ref, scrollValue, range) {
    let transformOpts = {};
    const {
      lerpFactor = 0.1,
      offset = -1.692,
      defaultOffset = 14,
    } = transformOpts;

    // if (deviceType === "desktop") {
    //   transformOpts = options.desktop || {};
    // } else if (deviceType === "mobileLandscape") {
    //   transformOpts = options.mobileLandscape || {};
    // } else if (deviceType === "tabletLandscape") {
    //   transformOpts = options.tabletLandscape || {};
    // } else {
    //   transformOpts = options.mobile || {};
    // }

    if (!ref.current) return;

    const isActive = scrollValue >= range[0] && scrollValue <= range[1];

    ref.current.traverse((child) => {
      if (child.isMesh) {
        // Z-Position
        const targetZ = isActive ? defaultOffset + offset : defaultOffset;
        child.position.z = THREE.MathUtils.lerp(
          child.position.z,
          targetZ,
          lerpFactor
        );
      }
    });
  }

  // function animateHighlight(ref, scrollValue, range, options = {}) {
  //   let transformOpts = {};

  //   if (deviceType === "desktop") {
  //     transformOpts = options.desktop || {};
  //   } else if (deviceType === "mobileLandscape") {
  //     transformOpts = options.mobileLandscape || {};
  //   } else if (deviceType === "tabletLandscape") {
  //     transformOpts = options.tabletLandscape || {};
  //   } else {
  //     transformOpts = options.mobile || {};
  //   }

  //   const {
  //     scale = 1.1,
  //     defaultScale = 1,
  //     lerpFactor = 0.1,
  //     defaultZ = -9.034,
  //     zOffset = 1,
  //     defaultX = -4.186,
  //     xOffset = -0.5,
  //     needRotate = false,
  //     defaultRotate = -4.186,
  //     rotateOffset = 0,
  //   } = transformOpts;

  //   if (!ref.current) return;

  //   const isActive = scrollValue >= range[0] && scrollValue <= range[1];

  //   ref.current.traverse((child) => {
  //     const name = child.name || "";

  //     const isBlack = name.endsWith("Black");
  //     const isNeonGreen = name.endsWith("NeonGreen");
  //     const isNeonAqua = name.endsWith("NeonAqua");
  //     const isNeonOrange = name.endsWith("NeonOrange");

  //     // Non Touch Devices
  //     if (child.isMesh && deviceType === "desktop") {
  //       //green
  //       if (isNeonGreen) {
  //         const targetColor = new THREE.Color(isActive ? "#FFAE95" : "#00C98C");

  //         // Smooth emissive color
  //         child.material.emissive.lerp(targetColor, lerpFactor);

  //         // Smooth base color
  //         child.material.color.lerp(targetColor, lerpFactor);

  //         // Smooth opacity
  //         const targetOpacity = isActive ? 0.7 : 0.3;
  //         child.material.opacity = THREE.MathUtils.lerp(
  //           child.material.opacity,
  //           targetOpacity,
  //           lerpFactor
  //         );

  //         child.material.needsUpdate = true;
  //       }

  //       //aqua
  //       if (isNeonAqua) {
  //         const targetIntensity = isActive ? 0.5 : 0.1;
  //         child.material.emissiveIntensity = THREE.MathUtils.lerp(
  //           child.material.emissiveIntensity,
  //           targetIntensity,
  //           lerpFactor
  //         );
  //         child.material.needsUpdate = true;
  //       }

  //       //orange
  //       if (isNeonOrange) {
  //         const targetColor = new THREE.Color(isActive ? "#00C98C" : "#FFAE95");

  //         child.material.emissive.lerp(targetColor, lerpFactor);
  //         child.material.color.lerp(targetColor, lerpFactor);

  //         // Optional: smoothly update emissive intensity too
  //         const targetIntensity = isActive ? 0.5 : 0.1;
  //         child.material.emissiveIntensity = THREE.MathUtils.lerp(
  //           child.material.emissiveIntensity,
  //           targetIntensity,
  //           lerpFactor
  //         );

  //         child.material.needsUpdate = true;
  //       }

  //       //  Black with color change
  //       if (isBlack) {
  //         if (isActive) {
  //           child.material.map = null; // disable texture
  //           child.material.color.set("#000000"); // highlight color
  //         } else {
  //           child.material.map = justBakedMaterial.map; // reassign texture
  //           child.material.color.set("#ffffff"); // neutral for map
  //         }
  //         child.material.needsUpdate = true;
  //       }

  //       // Scale
  //       const currentScale = child.scale.x;
  //       const targetScale = isActive ? scale : defaultScale;
  //       const newScale = THREE.MathUtils.lerp(
  //         currentScale,
  //         targetScale,
  //         lerpFactor
  //       );
  //       child.scale.setScalar(newScale);

  //       // Z-Position
  //       const targetZ = isActive ? defaultZ + zOffset : defaultZ;
  //       child.position.z = THREE.MathUtils.lerp(
  //         child.position.z,
  //         targetZ,
  //         lerpFactor
  //       );

  //       // X-Position
  //       const targetX = isActive ? defaultX + xOffset : defaultX;
  //       child.position.x = THREE.MathUtils.lerp(
  //         child.position.x,
  //         targetX,
  //         lerpFactor
  //       );

  //       // Y-Position
  //       if (needRotate) {
  //         const targetY = isActive
  //           ? defaultRotate + rotateOffset
  //           : defaultRotate;
  //         child.rotation.y = THREE.MathUtils.lerp(
  //           child.rotation.y,
  //           targetY,
  //           lerpFactor
  //         );
  //       }
  //     }

  //     // Touch Devices Mobile Potrait
  //     if (child.isMesh && deviceType === "mobile") {
  //       // Scale

  //       const currentScale = child.scale.x;
  //       const targetScale = isActive ? scale : defaultScale;
  //       const newScale = THREE.MathUtils.lerp(
  //         currentScale,
  //         targetScale,
  //         lerpFactor
  //       );
  //       child.scale.setScalar(newScale);

  //       // Z-Position
  //       const targetZ = isActive ? defaultZ + zOffset : defaultZ;
  //       child.position.z = THREE.MathUtils.lerp(
  //         child.position.z,
  //         targetZ,
  //         lerpFactor
  //       );

  //       // X-Position
  //       const targetX = isActive ? defaultX + xOffset : defaultX;
  //       child.position.x = THREE.MathUtils.lerp(
  //         child.position.x,
  //         targetX,
  //         lerpFactor
  //       );

  //       // X-Rotation
  //       if (needRotate) {
  //         const targetX = isActive
  //           ? defaultRotate + rotateOffset
  //           : defaultRotate;
  //         child.rotation.x = THREE.MathUtils.lerp(
  //           child.rotation.x,
  //           targetX,
  //           lerpFactor
  //         );
  //       }
  //     }

  //     // Touch Devices Mobile Lamdnscape
  //     if (
  //       child.isMesh &&
  //       (deviceType === "mobileLandscape" || deviceType === "tabletLandscape")
  //     ) {
  //       // Scale
  //       const currentScale = child.scale.x;
  //       const targetScale = isActive ? scale : defaultScale;
  //       const newScale = THREE.MathUtils.lerp(
  //         currentScale,
  //         targetScale,
  //         lerpFactor
  //       );
  //       child.scale.setScalar(newScale);

  //       // Z-Position
  //       const targetZ = isActive ? defaultZ + zOffset : defaultZ;
  //       child.position.z = THREE.MathUtils.lerp(
  //         child.position.z,
  //         targetZ,
  //         lerpFactor
  //       );

  //       // X-Position
  //       const targetX = isActive ? defaultX + xOffset : defaultX;
  //       child.position.x = THREE.MathUtils.lerp(
  //         child.position.x,
  //         targetX,
  //         lerpFactor
  //       );

  //       // Y-Rotation
  //       if (needRotate) {
  //         const targetY = isActive
  //           ? defaultRotate + rotateOffset
  //           : defaultRotate;
  //         child.rotation.y = THREE.MathUtils.lerp(
  //           child.rotation.y,
  //           targetY,
  //           lerpFactor
  //         );
  //       }
  //     }
  //   });
  // }

  function applyTransformations({
    child,
    isActive,
    scale,
    defaultScale,
    defaultZ,
    zOffset,
    defaultX,
    xOffset,
    defaultRotate,
    rotateOffset,
    lerpFactor,
    rotateAxis = "y",
    needRotate,
  }) {
    // Scale
    const currentScale = child.scale.x;
    const targetScale = isActive ? scale : defaultScale;
    const newScale = THREE.MathUtils.lerp(
      currentScale,
      targetScale,
      lerpFactor
    );
    child.scale.setScalar(newScale);

    // Z
    const targetZ = isActive ? defaultZ + zOffset : defaultZ;
    child.position.z = THREE.MathUtils.lerp(
      child.position.z,
      targetZ,
      lerpFactor
    );

    // X
    const targetX = isActive ? defaultX + xOffset : defaultX;
    child.position.x = THREE.MathUtils.lerp(
      child.position.x,
      targetX,
      lerpFactor
    );

    // Rotation
    if (needRotate) {
      const targetRotate = isActive
        ? defaultRotate + rotateOffset
        : defaultRotate;
      child.rotation[rotateAxis] = THREE.MathUtils.lerp(
        child.rotation[rotateAxis],
        targetRotate,
        lerpFactor
      );
    }
  }

  function animateHighlight(ref, scrollValue, range, options = {}) {
    let transformOpts = {};

    if (deviceType === "desktop") {
      transformOpts = options.desktop || {};
    } else if (deviceType === "mobileLandscape") {
      transformOpts = options.mobileLandscape || {};
    } else if (deviceType === "tabletLandscape") {
      transformOpts = options.tabletLandscape || {};
    } else {
      transformOpts = options.mobile || {};
    }

    const {
      scale = 1.1,
      defaultScale = 1,
      lerpFactor = 0.1,
      defaultZ = -9.034,
      zOffset = 1,
      defaultX = -4.186,
      xOffset = -0.5,
      needRotate = false,
      defaultRotate = -4.186,
      rotateOffset = 0,
    } = transformOpts;

    if (!ref.current) return;

    const isActive = scrollValue >= range[0] && scrollValue <= range[1];

    const commonTransformParams = {
      isActive,
      scale,
      defaultScale,
      defaultZ,
      zOffset,
      defaultX,
      xOffset,
      defaultRotate,
      rotateOffset,
      lerpFactor,
      needRotate,
      rotateAxis: deviceType === "mobile" ? "x" : "y",
    };

    ref.current.traverse((child) => {
      const name = child.name || "";

      const isBlack = name.endsWith("Black");
      const isNeonGreen = name.endsWith("NeonGreen");
      const isNeonAqua = name.endsWith("NeonAqua");
      const isNeonOrange = name.endsWith("NeonOrange");

      // Non Touch Devices
      if (child.isMesh && deviceType === "desktop") {
        //green
        if (isNeonGreen) {
          const targetColor = new THREE.Color(isActive ? "#FFAE95" : "#00C98C");

          // Smooth emissive color
          child.material.emissive.lerp(targetColor, lerpFactor);

          // Smooth base color
          child.material.color.lerp(targetColor, lerpFactor);

          // Smooth opacity
          const targetOpacity = isActive ? 0.7 : 0.3;
          child.material.opacity = THREE.MathUtils.lerp(
            child.material.opacity,
            targetOpacity,
            lerpFactor
          );

          child.material.needsUpdate = true;
        }

        //aqua
        if (isNeonAqua) {
          const targetIntensity = isActive ? 0.5 : 0.1;
          child.material.emissiveIntensity = THREE.MathUtils.lerp(
            child.material.emissiveIntensity,
            targetIntensity,
            lerpFactor
          );
          child.material.needsUpdate = true;
        }

        //orange
        if (isNeonOrange) {
          const targetColor = new THREE.Color(isActive ? "#00C98C" : "#FFAE95");

          child.material.emissive.lerp(targetColor, lerpFactor);
          child.material.color.lerp(targetColor, lerpFactor);

          // Optional: smoothly update emissive intensity too
          const targetIntensity = isActive ? 0.5 : 0.1;
          child.material.emissiveIntensity = THREE.MathUtils.lerp(
            child.material.emissiveIntensity,
            targetIntensity,
            lerpFactor
          );

          child.material.needsUpdate = true;
        }

        //  Black with color change
        if (isBlack) {
          if (isActive) {
            child.material.map = null; // disable texture
            child.material.color.set("#000000"); // highlight color
          } else {
            child.material.map = justBakedMaterial.map; // reassign texture
            child.material.color.set("#ffffff"); // neutral for map
          }
          child.material.needsUpdate = true;
        }

        applyTransformations({ child, ...commonTransformParams });

        // // Scale
        // const currentScale = child.scale.x;
        // const targetScale = isActive ? scale : defaultScale;
        // const newScale = THREE.MathUtils.lerp(
        //   currentScale,
        //   targetScale,
        //   lerpFactor
        // );
        // child.scale.setScalar(newScale);

        // // Z-Position
        // const targetZ = isActive ? defaultZ + zOffset : defaultZ;
        // child.position.z = THREE.MathUtils.lerp(
        //   child.position.z,
        //   targetZ,
        //   lerpFactor
        // );

        // // X-Position
        // const targetX = isActive ? defaultX + xOffset : defaultX;
        // child.position.x = THREE.MathUtils.lerp(
        //   child.position.x,
        //   targetX,
        //   lerpFactor
        // );

        // // Y-Position
        // if (needRotate) {
        //   const targetY = isActive
        //     ? defaultRotate + rotateOffset
        //     : defaultRotate;
        //   child.rotation.y = THREE.MathUtils.lerp(
        //     child.rotation.y,
        //     targetY,
        //     lerpFactor
        //   );
        // }
      }

      // Touch Devices Mobile Potrait
      if (child.isMesh && deviceType === "mobile") {
        // Scale
        applyTransformations({ child, ...commonTransformParams });
        // const currentScale = child.scale.x;
        // const targetScale = isActive ? scale : defaultScale;
        // const newScale = THREE.MathUtils.lerp(
        //   currentScale,
        //   targetScale,
        //   lerpFactor
        // );
        // child.scale.setScalar(newScale);

        // // Z-Position
        // const targetZ = isActive ? defaultZ + zOffset : defaultZ;
        // child.position.z = THREE.MathUtils.lerp(
        //   child.position.z,
        //   targetZ,
        //   lerpFactor
        // );

        // // X-Position
        // const targetX = isActive ? defaultX + xOffset : defaultX;
        // child.position.x = THREE.MathUtils.lerp(
        //   child.position.x,
        //   targetX,
        //   lerpFactor
        // );

        //  // X-Rotation
        // if (needRotate) {
        //   const targetX = isActive
        //     ? defaultRotate + rotateOffset
        //     : defaultRotate;
        //   child.rotation.x = THREE.MathUtils.lerp(
        //     child.rotation.x,
        //     targetX,
        //     lerpFactor
        //   );
        // }
      }

      // Touch Devices Mobile Lamdnscape
      if (
        child.isMesh &&
        (deviceType === "mobileLandscape" || deviceType === "tabletLandscape")
      ) {
        applyTransformations({ child, ...commonTransformParams });
        // // Scale
        // const currentScale = child.scale.x;
        // const targetScale = isActive ? scale : defaultScale;
        // const newScale = THREE.MathUtils.lerp(
        //   currentScale,
        //   targetScale,
        //   lerpFactor
        // );
        // child.scale.setScalar(newScale);

        // // Z-Position
        // const targetZ = isActive ? defaultZ + zOffset : defaultZ;
        // child.position.z = THREE.MathUtils.lerp(
        //   child.position.z,
        //   targetZ,
        //   lerpFactor
        // );

        // // X-Position
        // const targetX = isActive ? defaultX + xOffset : defaultX;
        // child.position.x = THREE.MathUtils.lerp(
        //   child.position.x,
        //   targetX,
        //   lerpFactor
        // );

        // // Y-Rotation
        // if (needRotate) {
        //   const targetY = isActive
        //     ? defaultRotate + rotateOffset
        //     : defaultRotate;
        //   child.rotation.y = THREE.MathUtils.lerp(
        //     child.rotation.y,
        //     targetY,
        //     lerpFactor
        //   );
        // }
      }
    });
  }

  useFrame(() => {
    const scrollValue = scroll.current * 100;

    animateText(textRef, scrollValue, [86, 95], {
      offset: -1.692,
      defaultOffset: 14,
    });

    animateHighlight(swifinRef, scrollValue, [9, 11.5], {
      desktop: {
        scale: 1.1,
        zOffset: 1.5,
        xOffset: -0.8,
        defaultZ: -9.034,
        defaultX: -4.186,
      },
      mobile: {
        scale: 1.25,
        zOffset: 0.4,
        xOffset: 0,
        defaultZ: -9.034,
        defaultX: -4.186,
      },
      mobileLandscape: {
        scale: 1.15,
        zOffset: 1.5,
        xOffset: 0,
        defaultZ: -9.034,
        defaultX: -4.186,
      },
      tabletLandscape: {
        scale: 1.05,
        zOffset: 1,
        xOffset: -0.75,
        defaultZ: -9.034,
        defaultX: -4.186,
      },
    });

    animateHighlight(mugavariRef, scrollValue, [12, 13.75], {
      desktop: {
        scale: 1.1,
        zOffset: 1.5,
        xOffset: -0.9,
        defaultZ: -8.976,
        defaultX: -5.017,
      },
      mobile: {
        scale: 1.25,
        zOffset: 0.4,
        xOffset: 0.05,
        defaultZ: -8.976,
        defaultX: -5.017,
      },
      mobileLandscape: {
        scale: 1.2,
        zOffset: 1.5,
        xOffset: 0.2,
        defaultZ: -8.976,
        defaultX: -5.017,
      },
      tabletLandscape: {
        scale: 1.1,
        zOffset: 1,
        xOffset: 0,
        defaultZ: -8.976,
        defaultX: -5.017,
      },
    });

    animateHighlight(amazonRef, scrollValue, [15.5, 17], {
      desktop: {
        scale: 1.1,
        zOffset: 1.25,
        xOffset: -0.6,
        defaultZ: -8.965,
        defaultX: -4.448,
        needRotate: true,
        rotateOffset: -0.2,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1.25,
        zOffset: 0.6,
        xOffset: -0.1,
        defaultZ: -8.965,
        defaultX: -4.448,
        needRotate: true,
        rotateOffset: 0.3,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.15,
        zOffset: 1,
        xOffset: 0.15,
        defaultZ: -8.965,
        defaultX: -4.448,
        needRotate: true,
        rotateOffset: -0.35,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.15,
        zOffset: 1,
        xOffset: -0.6,
        defaultZ: -8.965,
        defaultX: -4.448,
        needRotate: true,
        rotateOffset: -0.35,
        defaultRotate: 0,
      },
    });

    animateHighlight(wowhrRef, scrollValue, [18.5, 20.5], {
      desktop: {
        scale: 1.05,
        zOffset: 0.75,
        xOffset: -0.2,
        defaultZ: -9.021,
        defaultX: -1.057,
      },
      mobile: {
        scale: 1.2,
        zOffset: 0.5,
        xOffset: -0,
        defaultZ: -9.021,
        defaultX: -1.057,
      },
      mobileLandscape: {
        scale: 1.2,
        zOffset: 1.5,
        xOffset: -0.1,
        defaultZ: -9.021,
        defaultX: -1.057,
      },
      tabletLandscape: {
        scale: 1.2,
        zOffset: 1,
        xOffset: -0.1,
        defaultZ: -9.021,
        defaultX: -1.057,
      },
    });

    animateHighlight(xodaRef, scrollValue, [22, 23.75], {
      desktop: {
        scale: 1.05,
        zOffset: 1,
        xOffset: -0.6,
        defaultZ: -8.955,
        defaultX: -0.977,
      },
      mobile: {
        scale: 1.15,
        zOffset: 1,
        xOffset: 0,
        defaultZ: -8.955,
        defaultX: -0.977,
      },
      mobileLandscape: {
        scale: 1.15,
        zOffset: 2,
        xOffset: 0,
        defaultZ: -8.955,
        defaultX: -0.977,
      },
      tabletLandscape: {
        scale: 1.15,
        zOffset: 0.5,
        xOffset: 0.2,
        defaultZ: -8.955,
        defaultX: -0.977,
      },
    });

    animateHighlight(ad2dRef, scrollValue, [25, 26.75], {
      desktop: {
        scale: 1,
        zOffset: 1.5,
        xOffset: 0.9,
        defaultZ: -9,
        defaultX: 0.186,
        needRotate: true,
        rotateOffset: 0.4,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1.2,
        zOffset: 1.3,
        xOffset: 0,
        defaultZ: -9,
        defaultX: 0.186,
        needRotate: true,
        rotateOffset: 0.35,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.2,
        zOffset: 1.5,
        xOffset: -0,
        defaultZ: -9,
        defaultX: 0.186,
        needRotate: true,
        rotateOffset: -0.35,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.1,
        zOffset: 1,
        xOffset: -0,
        defaultZ: -9,
        defaultX: 0.186,
        needRotate: true,
        rotateOffset: 0.35,
        defaultRotate: 0,
      },
    });

    animateHighlight(spaceRef, scrollValue, [27.5, 29], {
      desktop: {
        scale: 1.1,
        zOffset: 1.5,
        xOffset: -1,
        defaultZ: -9.001,
        defaultX: -0.602,
        needRotate: true,
        rotateOffset: -0.2,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1.1,
        zOffset: 2,
        xOffset: 0.25,
        defaultZ: -9.001,
        defaultX: -0.602,
        needRotate: true,
        rotateOffset: 0.2,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.15,
        zOffset: 2,
        xOffset: -0.25,
        defaultZ: -9.001,
        defaultX: -0.602,
        needRotate: true,
        rotateOffset: -0.35,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.1,
        zOffset: 0.75,
        xOffset: -0.25,
        defaultZ: -9.001,
        defaultX: -0.602,
        needRotate: true,
        rotateOffset: -0.35,
        defaultRotate: 0,
      },
    });

    animateHighlight(ecommerceRef, scrollValue, [32.5, 34.5], {
      desktop: {
        scale: 1.1,
        zOffset: 1,
        xOffset: 0.5,
        defaultZ: -8.946,
        defaultX: 2.769,
        needRotate: true,
        rotateOffset: 0.2,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1.1,
        zOffset: 1,
        xOffset: 0,
        defaultZ: -8.946,
        defaultX: 2.769,
        needRotate: true,
        rotateOffset: 0.2,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.2,
        zOffset: 1.5,
        xOffset: -0.35,
        defaultZ: -8.946,
        defaultX: 2.769,
        needRotate: true,
        rotateOffset: -0.35,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.2,
        zOffset: 1,
        xOffset: 0.3,
        defaultZ: -8.946,
        defaultX: 2.769,
        needRotate: true,
        rotateOffset: 0.35,
        defaultRotate: 0,
      },
    });

    animateHighlight(portalRef, scrollValue, [36, 37.7], {
      desktop: {
        scale: 1.1,
        zOffset: 1.5,
        xOffset: 0.3,
        defaultZ: -8.998,
        defaultX: 4.162,
        needRotate: true,
        rotateOffset: 0.3,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1.1,
        zOffset: 1,
        xOffset: -0,
        defaultZ: -8.998,
        defaultX: 4.162,
        needRotate: true,
        rotateOffset: 0.3,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.2,
        zOffset: 2,
        xOffset: -0.65,
        defaultZ: -8.998,
        defaultX: 4.162,
        needRotate: true,
        rotateOffset: -0.6,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.1,
        zOffset: 1.2,
        xOffset: -0,
        defaultZ: -8.998,
        defaultX: 4.162,
        needRotate: true,
        rotateOffset: 0.4,
        defaultRotate: 0,
      },
    });

    animateHighlight(fjordRef, scrollValue, [39.5, 41.5], {
      desktop: {
        scale: 1.1,
        zOffset: 1,
        xOffset: -0.85,
        defaultZ: -9.001,
        defaultX: 2.588,
        needRotate: false,
        rotateOffset: 0,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1.1,
        zOffset: 1,
        xOffset: 0,
        defaultZ: -9.001,
        defaultX: 2.588,
        needRotate: false,
        rotateOffset: -0,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.2,
        zOffset: 2,
        xOffset: -0.2,
        defaultZ: -9.001,
        defaultX: 2.588,
        needRotate: false,
        rotateOffset: -0,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.1,
        zOffset: 1,
        xOffset: -0.35,
        defaultZ: -9.001,
        defaultX: 2.588,
        needRotate: false,
        rotateOffset: 0,
        defaultRotate: 0,
      },
    });

    animateHighlight(gameBoyRef, scrollValue, [43, 47], {
      desktop: {
        scale: 1,
        zOffset: 1.5,
        xOffset: -0,
        defaultZ: -8.646,
        defaultX: 6.217,
        needRotate: true,
        rotateOffset: 0.225,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1,
        zOffset: 1,
        xOffset: -0.3,
        defaultZ: -8.646,
        defaultX: 6.217,
        needRotate: true,
        rotateOffset: 0.3,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.15,
        zOffset: 1,
        xOffset: 0,
        defaultZ: -8.646,
        defaultX: 6.217,
        needRotate: true,
        rotateOffset: -0.6,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.15,
        zOffset: 1,
        xOffset: 0,
        defaultZ: -8.646,
        defaultX: 6.217,
        needRotate: true,
        rotateOffset: 0.4,
        defaultRotate: 0,
      },
    });

    animateHighlight(adminRef, scrollValue, [49, 50.5], {
      desktop: {
        scale: 1,
        zOffset: 0.7,
        xOffset: 0,
        defaultZ: -9.021,
        defaultX: 2.359,
        needRotate: false,
        rotateOffset: 0,
        defaultRotate: 0,
      },
      mobile: {
        scale: 1.15,
        zOffset: 0.7,
        xOffset: -0,
        defaultZ: -9.021,
        defaultX: 2.359,
        needRotate: false,
        rotateOffset: -0,
        defaultRotate: 0,
      },
      mobileLandscape: {
        scale: 1.25,
        zOffset: 1.25,
        xOffset: -0.25,
        defaultZ: -9.021,
        defaultX: 2.359,
        needRotate: false,
        rotateOffset: -0,
        defaultRotate: 0,
      },
      tabletLandscape: {
        scale: 1.1,
        zOffset: 0.75,
        xOffset: 0.05,
        defaultZ: -9.021,
        defaultX: 2.359,
        needRotate: false,
        rotateOffset: -0,
        defaultRotate: 0,
      },
    });
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <PerspectiveCamera
        name="Camera"
        makeDefault
        //   makeDefault={false}
        // far={1000}
        far={800}
        near={0.1}
        fov={fov}
        // fov={50}
        // fov={40}
        position={[-12.86, 7.66, 1.45]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <group name="Scene" ref={sceneRef}>
        <mesh
          name="JustMatteWhitePlane"
          geometry={nodes.JustMatteWhitePlane.geometry}
          material={justBakedMaterial}
        />
        <mesh
          name="JustMatteBlackPlane"
          geometry={nodes.JustMatteBlackPlane.geometry}
          material={justBakedMaterial}
        />

        <mesh
          name="Fan3"
          ref={fan3Ref}
          geometry={nodes.Fan3.geometry}
          material={justBakedMaterial}
          position={[-10.387, 2.986, -1.749]}
        />
        <mesh
          name="Fan1"
          ref={fan1Ref}
          geometry={nodes.Fan1.geometry}
          material={justBakedMaterial}
          position={[-10.387, 4.13, -1.749]}
        />
        <mesh
          name="Fan2"
          ref={fan2Ref}
          geometry={nodes.Fan2.geometry}
          material={justBakedMaterial}
          position={[-10.387, 3.551, -1.749]}
        />
        <mesh
          name="Fan4Neon"
          ref={fan4Ref}
          geometry={nodes.Fan4Neon.geometry}
          material={nodes.Fan4Neon.material}
          position={[-10.958, 3.033, -1.833]}
        >
          <meshStandardMaterial
            color={"#79FFFF"}
            emissive={"#79FFFF"}
            emissiveIntensity={0.1}
          />
        </mesh>
        <mesh
          name="JustRedPlane"
          geometry={nodes.JustRedPlane.geometry}
          material={justBakedMaterial}
        />
        <mesh
          name="JustMatteDarkGrayPlane"
          geometry={nodes.JustMatteDarkGrayPlane.geometry}
          material={justBakedMaterial}
        />
        <mesh
          name="JustExactMatteBlackPlane"
          geometry={nodes.JustExactMatteBlackPlane.geometry}
          material={justBakedMaterial}
        />
        <mesh
          name="JustMatteGrayPlane"
          geometry={nodes.JustMatteGrayPlane.geometry}
          material={justBakedMaterial}
        />
        <mesh
          name="JustPurplePlane"
          geometry={nodes.JustPurplePlane.geometry}
          material={justBakedMaterial}
        />
        {/*  */}
        <mesh
          name="NeonAquaPlane"
          ref={bloomRef}
          geometry={nodes.NeonAquaPlane.geometry}
        >
          <meshStandardMaterial
            color={"#79FFFF"}
            emissive={"#79FFFF"}
            emissiveIntensity={0.1}
          />
        </mesh>
        <mesh
          ref={textRef}
          name="NeonAquaPlaneText"
          geometry={nodes.NeonAquaPlaneText.geometry}
          // position={[3.184, 8.749, 12.308]}
          position={[3.184, 8.749, 14]}
        >
          <meshStandardMaterial color={"#292929"} />
        </mesh>

        <mesh
          name="NeonAquaExtraPlane"
          geometry={nodes.NeonAquaExtraPlane.geometry}
          material={nodes.NeonAquaExtraPlane.material}
        >
          <meshStandardMaterial
            color={"#79FFFF"}
            emissive={"#79FFFF"}
            emissiveIntensity={0.1}
          />
        </mesh>
        <mesh name="NeonOrangePlane" geometry={nodes.NeonOrangePlane.geometry}>
          <meshStandardMaterial
            color={"#FFAE95"}
            emissive={"#FFAE95"}
            emissiveIntensity={0.1}
          />
        </mesh>
        <mesh
          name="NeonWhitePlane"
          geometry={nodes.NeonWhitePlane.geometry}
          material={nodes.NeonWhitePlane.material}
        >
          <meshStandardMaterial
            color={"#FFFFFF"}
            emissive={"#FFFFFF"}
            emissiveIntensity={0.1}
          />
        </mesh>
        {/*  */}

        {/*  */}
        <mesh
          name="TransparentPlane"
          geometry={nodes.TransparentPlane.geometry}
          material={nodes.TransparentPlane.material}
        >
          <meshStandardMaterial
            color="white"
            transparent
            roughness={0.05}
            opacity={0} // fully transparent
          />
        </mesh>
        {/*  */}

        {/*  */}
        <mesh
          name="DragonOuterPlane"
          geometry={nodes.DragonOuterPlane.geometry}
          material={nodes.DragonOuterPlane.material}
          position={[-11.909, 3.059, 2.558]}
          renderOrder={999}
        >
          <dragonBallGlowMaterial
            attach="material"
            transparent
            depthWrite={false}
            blending={THREE.AdditiveBlending}
            side={THREE.DoubleSide}
            intensity={2}
          />
        </mesh>
        <mesh
          name="DragonInnerPlane"
          geometry={nodes.DragonInnerPlane.geometry}
          material={nodes.DragonInnerPlane.material}
          scale={[1.45, 1.45, 1.45]}
          position={[-11.909, 3.059, 2.558]}
        >
          {/* <meshStandardMaterial
            color="#FF8312"
            transparent
            opacity={0.3}
            emissive="#FF8312"
            emissiveIntensity={0.1}
          /> */}
          <meshStandardMaterial
            color="#FF7A00"
            emissive="#FF7A00"
            emissiveIntensity={1.25}
            // emissiveIntensity={1.8}
            transparent
            opacity={0.6}
            roughness={0}
            metalness={0}
            // blending={THREE.AdditiveBlending}
            depthWrite={false}
          />
        </mesh>
        <mesh
          name="DragonStarPlane"
          geometry={nodes.DragonStarPlane.geometry}
          material={nodes.DragonStarPlane.material}
          position={[-11.889, 3.096, 2.593]}
          rotation={[0.891, 0.343, -1.976]}
          scale={[1.5, 1.5, 1.5]}
          renderOrder={1000}
        >
          <meshStandardMaterial
            color="#FF0000"
            emissive="#FF0000"
            emissiveIntensity={0.1} // 🔥 Stronger
            // toneMapped={false}
            transparent={true}
            // opacity={1}
            depthWrite={true} // ✅ Needed to avoid rendering behind shells
            // blending={THREE.NormalBlending} // ✅ Don't add it up like glow
          />
        </mesh>
        {/*  */}
        <mesh
          name="GohanPlane"
          geometry={nodes.GohanPlane.geometry}
          position={[-12.314, 7.181, -8.569]}
          rotation={[-0.15, -0.023, 0.147]}
        >
          <meshStandardMaterial map={gohanMaterial} />
        </mesh>
        {/* Clock Start */}
        <mesh
          ref={minuteRef}
          name="clockMinute"
          geometry={nodes.clockMinute.geometry}
          position={[3.211, 10.185, 12.236]}
        >
          <meshStandardMaterial color={"#79FFFF"} />
        </mesh>
        <mesh
          ref={hourRef}
          name="clockHour"
          geometry={nodes.clockHour.geometry}
          position={[3.211, 10.185, 12.236]}
        >
          <meshStandardMaterial color={"#79FFFF"} />
        </mesh>
        <mesh
          ref={secondRef}
          name="clockSecond"
          geometry={nodes.clockSecond.geometry}
          position={[3.211, 10.185, 12.236]}
        >
          <meshStandardMaterial color={"#79FFFF"} />
        </mesh>
        <mesh
          name="clockStop"
          geometry={nodes.clockStop.geometry}
          position={[3.211, 10.185, 12.233]}
        >
          <meshStandardMaterial color={"#79FFFF"} />
        </mesh>
        {/* Clock End */}
        {/*  */}
        <mesh
          name="Info"
          geometry={nodes.Info.geometry}
          position={[-10.907, 2.671, 2.221]}
          // rotation={[0, 0.496, 0]}
        >
          <meshStandardMaterial
            map={infoMaterial}
            roughness={1}
            metalness={0.5}
            color="#ffffff"
            emissive="#ffffff"
            emissiveIntensity={0.25}
          />
        </mesh>
        {/*  */}
        {/* Frame Start */}

        {/* Swifin Start */}
        <group ref={swifinRef}>
          <mesh
            name="SwifinPlane"
            position={[-4.186, 9.219, -9.034]}
            geometry={nodes.SwifinPlane.geometry}
          >
            <meshStandardMaterial map={swifinMaterial} />
          </mesh>
          <mesh
            name="SwifinNeonGreen"
            position={[-4.186, 9.219, -9.034]}
            geometry={nodes.SwifinNeonGreen.geometry}
          >
            <meshStandardMaterial
              color={"#00C98C"}
              // roughness={1}
              // metalness={0}
              transparent
              opacity={0.3}
              emissive={"#00C98C"}
              emissiveIntensity={0.1}
            />
          </mesh>{" "}
          <mesh
            name="SwifinNeonAqua"
            position={[-4.186, 9.219, -9.034]}
            geometry={nodes.SwifinNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="SwifinBlack"
            position={[-4.186, 9.219, -9.034]}
            geometry={nodes.SwifinBlack.geometry}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="SwifinNeonOrange"
            position={[-4.186, 9.219, -9.034]}
            geometry={nodes.SwifinNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Swifin End */}

        {/* Mugavari Start */}
        <group ref={mugavariRef}>
          <mesh
            name="MugavariPlane"
            geometry={nodes.MugavariPlane.geometry}
            position={[-5.017, 6.587, -8.976]}
          >
            <meshStandardMaterial map={mugavariMaterial} />
          </mesh>
          <mesh
            name="MugavariNeonAqua"
            position={[-5.017, 6.587, -8.976]}
            geometry={nodes.MugavariNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="MugavariBlack"
            position={[-5.017, 6.587, -8.976]}
            geometry={nodes.MugavariBlack.geometry}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="MugavariNeonOrange"
            position={[-5.017, 6.587, -8.976]}
            geometry={nodes.MugavariNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Mugavari End */}

        {/* Amazon Start */}
        <group ref={amazonRef}>
          <mesh
            name="AmazonPlane"
            geometry={nodes.AmazonPlane.geometry}
            position={[-4.448, 4.185, -8.965]}
          >
            <meshStandardMaterial map={amazonMaterial} />
          </mesh>
          <mesh
            name="AmazonNeonAqua"
            position={[-4.448, 4.185, -8.965]}
            geometry={nodes.AmazonNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="AmazonNeonGreen"
            position={[-4.448, 4.185, -8.965]}
            geometry={nodes.AmazonNeonGreen.geometry}
          >
            <meshStandardMaterial
              color={"#00C98C"}
              transparent
              opacity={0.3}
              emissive={"#00C98C"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="AmazonBlack"
            position={[-4.448, 4.185, -8.965]}
            geometry={nodes.AmazonBlack.geometry}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="AmazonNeonOrange"
            position={[-4.448, 4.185, -8.965]}
            geometry={nodes.AmazonNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Amazon End */}

        {/* Wowhr Start */}
        <group ref={wowhrRef}>
          <mesh
            name="WowhrPlane"
            geometry={nodes.WowhrPlane.geometry}
            position={[-1.057, 3.487, -9.021]}
          >
            <meshStandardMaterial map={wowhrMaterial} />
          </mesh>
          <mesh
            name="WowhrNeonAqua"
            position={[-1.057, 3.487, -9.021]}
            geometry={nodes.WowhrNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="WowhrNeonGreen"
            position={[-1.057, 3.487, -9.021]}
            geometry={nodes.WowhrNeonGreen.geometry}
          >
            <meshStandardMaterial
              color={"#00C98C"}
              transparent
              opacity={0.3}
              emissive={"#00C98C"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="WowhrBlack"
            position={[-1.057, 3.487, -9.021]}
            geometry={nodes.WowhrBlack.geometry}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="WowhrNeonOrange"
            position={[-1.057, 3.487, -9.021]}
            geometry={nodes.WowhrNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Wowhr End */}

        {/* Xoda Start */}
        <group ref={xodaRef}>
          <mesh
            name="XodaPlane"
            geometry={nodes.XodaPlane.geometry}
            position={[-0.977, 5.776, -8.955]}
          >
            <meshStandardMaterial map={xodaMaterial} />
          </mesh>
          <mesh
            name="XodaNeonAqua"
            position={[-0.977, 5.776, -8.955]}
            geometry={nodes.XodaNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="XodaNeonGreen"
            position={[-0.977, 5.776, -8.955]}
            geometry={nodes.XodaNeonGreen.geometry}
          >
            <meshStandardMaterial
              color={"#00C98C"}
              // roughness={1}
              // metalness={0}
              transparent
              opacity={0.3}
              emissive={"#00C98C"}
              emissiveIntensity={0.1}
            />
          </mesh>{" "}
          <mesh
            name="XodaBlack"
            position={[-0.977, 5.776, -8.955]}
            geometry={nodes.XodaBlack.geometry}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="XodaNeonOrange"
            position={[-0.977, 5.776, -8.955]}
            geometry={nodes.XodaNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Xoda End */}

        {/* ad2d Start */}
        <group ref={ad2dRef}>
          <mesh
            name="ad2dPlane"
            geometry={nodes.ad2dPlane.geometry}
            position={[0.186, 8.142, -9]}
          >
            <meshStandardMaterial map={ad2dMaterial} />
          </mesh>
          <mesh
            name="ad2dNeonAqua"
            position={[0.186, 8.142, -9]}
            geometry={nodes.ad2dNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="ad2dBlack"
            position={[0.186, 8.142, -9]}
            geometry={nodes.ad2dBlack.geometry}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="ad2dNeonOrange"
            position={[0.186, 8.142, -9]}
            geometry={nodes.ad2dNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* ad2d End */}

        {/* Space Start */}
        <group ref={spaceRef}>
          <mesh
            name="SpacePlane"
            geometry={nodes.SpacePlane.geometry}
            position={[-0.602, 10.491, -9.001]}
          >
            <meshStandardMaterial map={spaceMaterial} />
          </mesh>
          <mesh
            name="SpaceNeonAqua"
            geometry={nodes.SpaceNeonAqua.geometry}
            position={[-0.602, 10.491, -9.001]}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="SpaceNeonGreen"
            geometry={nodes.SpaceNeonGreen.geometry}
            position={[-0.602, 10.491, -9.001]}
          >
            <meshStandardMaterial
              color={"#00C98C"}
              // roughness={1}
              // metalness={0}
              transparent
              opacity={0.3}
              emissive={"#00C98C"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="SpaceBlack"
            geometry={nodes.SpaceBlack.geometry}
            position={[-0.602, 10.491, -9.001]}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="SpaceNeonOrange"
            position={[-0.602, 10.491, -9.001]}
            geometry={nodes.SpaceNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Space End */}

        {/* Ecommerce Start */}
        <group ref={ecommerceRef}>
          <mesh
            name="EcommercePlane"
            geometry={nodes.EcommercePlane.geometry}
            position={[2.769, 10.288, -8.946]}
          >
            <meshStandardMaterial map={ecommerceMaterial} />
          </mesh>
          <mesh
            name="EcommerceNeonAqua"
            position={[2.769, 10.288, -8.946]}
            geometry={nodes.EcommerceNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="EcommerceBlack"
            position={[2.769, 10.288, -8.946]}
            geometry={nodes.EcommerceBlack.geometry}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="EcommerceNeonOrange"
            position={[2.769, 10.288, -8.946]}
            geometry={nodes.EcommerceNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Ecommerce End */}

        {/* Portal Start */}
        <group ref={portalRef}>
          <mesh
            name="PortalPlane"
            geometry={nodes.PortalPlane.geometry}
            material={nodes.PortalPlane.material}
            position={[4.162, 8.228, -8.998]}
          >
            <meshStandardMaterial map={portalMaterial} />
          </mesh>
          <mesh
            name="PortalNeonAqua"
            position={[4.162, 8.228, -8.998]}
            geometry={nodes.PortalNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="PortalBlack"
            position={[4.162, 8.228, -8.998]}
            geometry={nodes.PortalBlack.geometry}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="PortalNeonOrange"
            position={[4.162, 8.228, -8.998]}
            geometry={nodes.PortalNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Portal End */}

        {/* Fjord Start */}
        <group ref={fjordRef}>
          <mesh
            name="FjordPlane"
            geometry={nodes.FjordPlane.geometry}
            position={[2.588, 5.877, -9.001]}
          >
            <meshStandardMaterial map={fjordMaterial} />
          </mesh>
          <mesh
            name="FjordNeonAqua"
            position={[2.588, 5.877, -9.001]}
            geometry={nodes.FjordNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="FjordNeonGreen"
            position={[2.588, 5.877, -9.001]}
            geometry={nodes.FjordNeonGreen.geometry}
          >
            <meshStandardMaterial
              color={"#00C98C"}
              // roughness={1}
              // metalness={0}
              transparent
              opacity={0.3}
              emissive={"#00C98C"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="FjordBlack"
            position={[2.588, 5.877, -9.001]}
            geometry={nodes.FjordBlack.geometry}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="FjordNeonOrange"
            position={[2.588, 5.877, -9.001]}
            geometry={nodes.FjordNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* Fjord End */}

        {/* GameBoy Start */}
        <group ref={gameBoyRef}>
          <mesh
            name="Gameboy2Plane"
            geometry={nodes.Gameboy2Plane.geometry}
            position={[6.217, 5.641, -8.646]}
          >
            <meshStandardMaterial map={gb22Material} />
          </mesh>
          <mesh
            name="Gameboy1Plane"
            geometry={nodes.Gameboy1Plane.geometry}
            position={[6.217, 5.641, -8.646]}
          >
            <meshStandardMaterial map={gb11Material} />
          </mesh>
          <mesh
            name="GameboyNeonAqua"
            position={[6.217, 5.641, -8.646]}
            geometry={nodes.GameboyNeonAqua.geometry}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="GameboyBlack"
            position={[6.217, 5.641, -8.646]}
            geometry={nodes.GameboyBlack.geometry}
            // material={justBakedMaterial}
          >
            <meshStandardMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="GameboyNeonOrange"
            position={[6.217, 5.641, -8.646]}
            geometry={nodes.GameboyNeonOrange.geometry}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* GameBoy End */}

        {/* admin Start */}
        <group ref={adminRef}>
          <mesh
            name="AdminPlane"
            geometry={nodes.AdminPlane.geometry}
            material={nodes.AdminPlane.material}
            position={[2.359, 3.67, -9.021]}
          >
            <meshStandardMaterial map={adminMaterial} />
          </mesh>
          <mesh
            name="AdminAqua"
            geometry={nodes.AdminAqua.geometry}
            material={nodes.AdminAqua.material}
            position={[2.345, 3.67, -9.021]}
          >
            <meshStandardMaterial
              color={"#79FFFF"}
              emissive={"#79FFFF"}
              emissiveIntensity={0.1}
            />
          </mesh>

          <mesh
            name="AdminGreen"
            geometry={nodes.AdminGreen.geometry}
            material={nodes.AdminGreen.material}
            position={[2.359, 3.67, -9.021]}
          >
            <meshStandardMaterial
              color={"#00C98C"}
              // roughness={1}
              // metalness={0}
              transparent
              opacity={0.3}
              emissive={"#00C98C"}
              emissiveIntensity={0.1}
            />
          </mesh>
          <mesh
            name="AdminBlack"
            geometry={nodes.AdminBlack.geometry}
            material={nodes.AdminBlack.material}
            position={[2.359, 3.67, -9.021]}
          >
            <meshBasicMaterial map={justBakedMaterial.map} />
          </mesh>
          <mesh
            name="AdminOrange"
            geometry={nodes.AdminOrange.geometry}
            material={nodes.AdminOrange.material}
            position={[2.359, 3.67, -9.021]}
          >
            <meshStandardMaterial
              color={"#FFAE95"}
              emissive={"#FFAE95"}
              emissiveIntensity={0.1}
            />
          </mesh>
        </group>
        {/* admin End */}

        {/* Frame End */}

        <mesh
          name="ZoroPlane"
          geometry={nodes.ZoroPlane.geometry}
          position={[-12.356, 5.037, -8.588]}
          rotation={[-0.18, 0.098, 0.163]}
        >
          <meshStandardMaterial map={zoroMaterial} />
        </mesh>
        <mesh
          name="ItachiPlane"
          geometry={nodes.ItachiPlane.geometry}
          position={[-12.864, 6.994, -6.772]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <meshStandardMaterial map={itachiMaterial} />
        </mesh>
        <mesh
          name="LuffyPlane"
          geometry={nodes.LuffyPlane.geometry}
          position={[-12.864, 5.76, -5.187]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <meshStandardMaterial map={luffyMaterial} />
        </mesh>
        <mesh
          name="SpidyPlane"
          geometry={nodes.SpidyPlane.geometry}
          position={[-12.833, 6.994, -3.617]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <meshStandardMaterial map={spiderMaterial} />
        </mesh>
        <mesh
          name="BatmanPlane"
          geometry={nodes.BatmanPlane.geometry}
          position={[-12.838, 8.046, -5.19]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <meshStandardMaterial map={batmanMaterial} />
        </mesh>
        <mesh
          name="TvPlane"
          geometry={nodes.TvPlane.geometry}
          position={[11.614, 8.516, 1.622]}
          rotation={[0, 0, -1.463]}
        >
          <meshStandardMaterial map={tvImageMaterial} />
        </mesh>
        <mesh
          name="mySelfPlane"
          geometry={nodes.mySelfPlane.geometry}
          position={[-11.291, 3.732, 0.549]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <meshStandardMaterial
            map={introMaterial}
            roughness={1}
            metalness={0.15}
          />
        </mesh>
        <mesh
          name="HtmlPlane"
          geometry={nodes.HtmlPlane.geometry}
          material={nodes.HtmlPlane.material}
          position={[-11.068, 4.239, -6.057]}
          rotation={[1.67, 0.091, -1.066]}
        >
          <meshStandardMaterial map={htmlCssMaterial} />
        </mesh>
        <mesh
          name="ReactjsPlane"
          geometry={nodes.ReactjsPlane.geometry}
          position={[-10.727, 4.447, -6.613]}
          rotation={[1.567, -0.002, -0.822]}
        >
          <meshStandardMaterial map={reactjsMaterial} />
        </mesh>
        <mesh
          name="BlenderPlane"
          geometry={nodes.BlenderPlane.geometry}
          position={[-10.357, 4.307, -7.339]}
          rotation={[1.475, -0.052, -1.053]}
        >
          <meshStandardMaterial map={blenderMaterial} />
        </mesh>
        <mesh
          name="JavaScriptPlane"
          geometry={nodes.JavaScriptPlane.geometry}
          position={[-11.338, 3.713, -5.525]}
          rotation={[1.697, 0.059, -1.07]}
        >
          <meshStandardMaterial map={javascriptMaterial} />
        </mesh>
        <mesh
          name="SplinePlane"
          geometry={nodes.SplinePlane.geometry}
          position={[-10.896, 3.661, -6.364]}
          rotation={[-3.139, 0.541, -1.807]}
        >
          <meshStandardMaterial map={splineMaterial} />
        </mesh>
        <mesh
          name="ThreeJsPlane"
          geometry={nodes.ThreeJsPlane.geometry}
          position={[-10.794, 3.096, -6.521]}
          rotation={[1.753, 0.165, -1.072]}
        >
          <meshStandardMaterial map={threejsMaterial} />
        </mesh>
        <mesh
          name="GsapPlane"
          geometry={nodes.GsapPlane.geometry}
          position={[-11.238, 3.288, -5.745]}
          rotation={[3.079, 0.549, 2.34]}
        >
          <meshStandardMaterial map={gsapMaterial} />
        </mesh>
        <mesh
          name="TailwindCssPlane"
          geometry={nodes.TailwindCssPlane.geometry}
          position={[-8.571, 3.817, -5.918]}
          rotation={[0, 0.086, 0]}
        >
          <meshStandardMaterial map={tailwindcssMaterial} />
        </mesh>
        <mesh
          name="FigmaPlane"
          geometry={nodes.FigmaPlane.geometry}
          position={[-10.149, 3.918, -7.719]}
          rotation={[1.661, 0.048, -1.077]}
        >
          <meshStandardMaterial map={figmaMaterial} />
        </mesh>
        <mesh
          name="FlutterPlane"
          geometry={nodes.FlutterPlane.geometry}
          position={[-10.111, 3.114, -7.788]}
          rotation={[1.619, 0.026, -1.07]}
        >
          <meshStandardMaterial map={flutterMaterial} />
        </mesh>
        <mesh
          name="RatingPlane"
          geometry={nodes.RatingPlane.geometry}
          position={[-11.343, 4.384, -5.577]}
          rotation={[1.586, 0.008, -1.012]}
        >
          <meshStandardMaterial map={ratingsMaterial} />
        </mesh>
        <mesh
          name="UnityPlane"
          geometry={nodes.UnityPlane.geometry}
          position={[-10.357, 3.246, -7.331]}
          rotation={[1.523, -0.027, -1.068]}
        >
          <meshStandardMaterial map={unityMaterial} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/room2v2.2.glb");
